name: Build and Deploy Code
on: [push, pull_request] # on all branches

jobs:
  job1:
    runs-on: ubuntu-lastest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi
        run: echo "hello"
